filter:
    excluded_paths:
        - '*.min.js'
        - 'dist/*'
checks:
    javascript: true
build:
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run